-- MySQL Script generated by MySQL Workbench
-- Fri Aug 16 17:22:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nodebase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nodebase` ;

-- -----------------------------------------------------
-- Schema nodebase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nodebase` DEFAULT CHARACTER SET utf32 COLLATE utf32_spanish2_ci ;
USE `nodebase` ;

-- -----------------------------------------------------
-- Table `nodebase`.`rols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nodebase`.`rols` ;

CREATE TABLE IF NOT EXISTS `nodebase`.`rols` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nodebase`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nodebase`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `nodebase`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(100) NULL,
  `email` VARCHAR(60) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(60) NOT NULL,
  `imagen` VARCHAR(60) NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `rol_id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuarios_roles1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `nodebase`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nodebase`.`entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nodebase`.`entradas` ;

CREATE TABLE IF NOT EXISTS `nodebase`.`entradas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` VARCHAR(5) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_entradas_usuarios_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_entradas_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `nodebase`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `nodebase`.`rols`
-- -----------------------------------------------------
START TRANSACTION;
USE `nodebase`;
INSERT INTO `nodebase`.`rols` (`id`, `nombre`) VALUES (1, 'Admin');
INSERT INTO `nodebase`.`rols` (`id`, `nombre`) VALUES (2, 'Usuarios');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nodebase`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `nodebase`;
INSERT INTO `nodebase`.`usuarios` (`id`, `nombre`, `apellidos`, `email`, `alias`, `contrasena`, `imagen`, `activo`, `rol_id`) VALUES (1, 'admin', 'admin', 'admin@nodebase.es', 'admin', '$2b$10$U2WiUy7cCoAqKYJawH1ZmutBgHvEf1sJe1DFOBAXzie9pcEr1Vm8a', NULL, 1, 1);

COMMIT;

